<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Shto_User.aspx.cs" Inherits="Portali.Root.Shto_User" %>
<%@Register TagPrefix="meta" TagName="HeadA" Src="../Controls/HeadA.ascx" %>
<%@Register TagPrefix="meta" TagName="NavA" Src="../Controls/NavA.ascx" %>
<%@Register TagPrefix="meta" TagName="MenuA" Src="../Controls/MenuA.ascx" %>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta:HeadA runat="server"></meta:HeadA>  
</head>
<body class="fix-header">
    <meta:NavA runat="server"></meta:NavA>
        <meta:MenuA runat="server"></meta:MenuA>
      <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row bg-title">
                    <div class="col-lg-6 col-md-4 col-sm-4 col-xs-12">
                        <h1 id="H1" runat="server" class="page-title">Regjistroni një përdorues</h1> </div>
                </div>
     <div class="row" id="Permbajtje" runat="server"> 
    <form id="form1" cssclass="form-horizontal" runat="server">
        <div class="col-md-12 content">
       <div class="container" style="width:auto;">
         
             <div id="srch">
                 <div class="col-md-7">
                 <asp:DropDownList ID="DDL1" class="form-control btn btn-default" runat="server">
            <asp:ListItem>Student</asp:ListItem>
            <asp:ListItem>Pedagog</asp:ListItem>
        </asp:DropDownList>
                 <div class="input-group">
             <asp:TextBox ID="txt1" class="form-control" runat="server" ValidationGroup="G1" Placeholder="Kërko një përdorues"></asp:TextBox>
                     <div class="input-group-btn">
             <asp:Button ID="Button3" runat="server" class="btn btn-default" Text="Kerko" OnClick="Button3_Click" ValidationGroup="G1" CausesValidation="false" />
         <asp:Button ID="Button4" class="btn btn-default" runat="server" Text="< Kthehu" OnClick="Button4_Click" />
                     </div>
        </div> <br />  <br />  </div>
                      
                 <asp:GridView ID="Grid1" runat="server" AllowPaging="True" ShowFooter="true" OnRowCancelingEdit="Grid1_RowCancelingEdit" DataKeyNames="Username,Ssn,Emri,Atesia,Mbiemri,Email,NrKontakti,Titulli,Departamenti" Visible="False" OnRowUpdating="Grid1_RowUpdating"  AutoGenerateColumns="False" AllowSorting="True" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" OnRowDeleting="Grid1_RowDeleting" OnRowEditing="Grid1_RowEditing" CssClass= "table table-hover table-striped table-bordered table-condensed" style="font-size:13px;">
        <Columns>
            <asp:TemplateField HeaderText="Username" SortExpression="Username">
                <EditItemTemplate>
                    <asp:TextBox ID="USERNAME" runat="server" Text='<%# Bind("Username") %>'></asp:TextBox>
                </EditItemTemplate>
                <FooterTemplate>
                    &nbsp;
                </FooterTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("Username") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="SSN" SortExpression="Ssn">
                <EditItemTemplate>
                    <asp:TextBox ID="SSN" runat="server" Text='<%# Bind("Ssn") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label2" runat="server" Text='<%# Bind("Ssn") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="EMRI" SortExpression="Emri">
                <EditItemTemplate>
                    <asp:TextBox ID="EMRI" runat="server" Text='<%# Bind("Emri") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label3" runat="server" Text='<%# Bind("Emri") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="ATESIA" SortExpression="Atesia">
                <EditItemTemplate>
                    <asp:TextBox ID="ATESIA" runat="server" Text='<%# Bind("Atesia") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label4" runat="server" Text='<%# Bind("Atesia") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="MBIEMRI" SortExpression="Mbiemri">
                <EditItemTemplate>
                    <asp:TextBox ID="MBIEMRI" runat="server" Text='<%# Bind("Mbiemri") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label5" runat="server" Text='<%# Bind("Mbiemri") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="EMAIL" SortExpression="Email">
                <EditItemTemplate>
                    <asp:TextBox ID="EMAIL" runat="server" Text='<%# Bind("Email") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label6" runat="server" Text='<%# Bind("Email") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="NR.KONTAKTI" SortExpression="NrKontakti">
                <EditItemTemplate>
                    <asp:TextBox ID="NRKONTAKTI" runat="server" Text='<%# Bind("NrKontakti") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label7" runat="server" Text='<%# Bind("NrKontakti") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="TITULLI" SortExpression="Titulli">
                <EditItemTemplate>
                    <asp:TextBox ID="TITULLI" runat="server" Text='<%# Bind("Titulli") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label8" runat="server" Text='<%# Bind("Titulli") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="DEPARTAMENTI" SortExpression="Departamenti">
                <EditItemTemplate>
                    <asp:TextBox ID="DEPARTAMENTI" runat="server" Text='<%# Bind("Departamenti") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label9" runat="server" Text='<%# Bind("Departamenti") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>    
        </asp:GridView>
        <asp:GridView ID="Grid2" runat="server" DataKeyNames="Username,Ssn,Emri,Atesia,Mbiemri,Email,Viti,Grupi,Departamenti" OnRowCancelingEdit="Grid2_RowCancelingEdit" AllowPaging="True" Visible="False" OnRowUpdating="Grid2_RowUpdating"  AutoGenerateColumns="False" AllowSorting="True" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True"  OnRowDeleting="Grid2_RowDeleting" OnRowEditing="Grid2_RowEditing" CssClass= "table table-hover table-striped table-bordered table-condensed" style="font-size:13px;">
            <Columns>
                <asp:TemplateField HeaderText="USERNAME" SortExpression="Username">
                    <EditItemTemplate>
                        <asp:TextBox ID="USERNAMES" runat="server" Text='<%# Bind("Username") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("Username") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="SSN" SortExpression="Ssn">
                    <EditItemTemplate>
                        <asp:TextBox ID="SSNS" runat="server" Text='<%# Bind("Ssn") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("Ssn") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="EMRI" SortExpression="Emri">
                    <EditItemTemplate>
                        <asp:TextBox ID="EMRIS" runat="server" Text='<%# Bind("Emri") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("Emri") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="ATESIA" SortExpression="Atesia">
                    <EditItemTemplate>
                        <asp:TextBox ID="ATESIAS" runat="server" Text='<%# Bind("Atesia") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("Atesia") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="MBIEMRI" SortExpression="Mbiemri">
                    <EditItemTemplate>
                        <asp:TextBox ID="MBIEMRIS" runat="server" Text='<%# Bind("Mbiemri") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label5" runat="server" Text='<%# Bind("Mbiemri") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="EMAIL" SortExpression="Email">
                    <EditItemTemplate>
                        <asp:TextBox ID="EMAILS" runat="server" Text='<%# Bind("Email") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label6" runat="server" Text='<%# Bind("Email") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="VITI" SortExpression="Viti">
                    <EditItemTemplate>
                        <asp:TextBox ID="VITIS" runat="server" Text='<%# Bind("Viti") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label7" runat="server" Text='<%# Bind("Viti") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="GRUPI" SortExpression="Grupi">
                    <EditItemTemplate>
                        <asp:TextBox ID="GRUPIS" runat="server" Text='<%# Bind("Grupi") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label9" runat="server" Text='<%# Bind("Grupi") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="DEPARTAMENTI" SortExpression="Departamenti">
                    <EditItemTemplate>
                        <asp:TextBox ID="DEPARTAMENTIS" runat="server" Text='<%# Bind("Departamenti") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label8" runat="server" Text='<%# Bind("Departamenti") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
    </div>
             <div id="usr" runat="server">
        <asp:ValidationSummary runat="server" CssClass="text-danger" />
        <div class="form-group">
        <div class="col-md-7">
        Username<asp:TextBox ID="un" class="form-control" runat="server"></asp:TextBox>
        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" CssClass="text-danger" runat="server" ControlToValidate="un" Text="*" ErrorMessage="Plotësoni Username" ToolTip="Plotësoni Username" ForeColor="Red"></asp:RequiredFieldValidator>
        </div>
        </div>
        <div class="form-group">
        <div class="col-md-7">
        Password<asp:TextBox ID="passwordi" class="form-control" runat="server" />
        <asp:RequiredFieldValidator ID="RequiredFieldValidator2" CssClass="text-danger" runat="server" ControlToValidate="passwordi" Text="*" ErrorMessage="Plotësoni Password" ToolTip="Plotësoni Password" ForeColor="Red"></asp:RequiredFieldValidator>
        </div>
        </div>
        <div class="form-group">
        <div class="col-md-7">
        SSN<asp:TextBox ID="ssn" class="form-control" runat="server"></asp:TextBox>
        <asp:RequiredFieldValidator ID="RequiredFieldValidator3" CssClass="text-danger" runat="server" ControlToValidate="ssn" Text="*" ErrorMessage="Plotësoni SSN" ToolTip="Plotësoni SSN" ForeColor="Red"></asp:RequiredFieldValidator>
        </div>
        </div>
        <div class="form-group">
        <div class="col-md-7">
        Roli<asp:DropDownList ID="rol" runat="server" class="form-control btn btn-default">
              <asp:ListItem>ADMIN</asp:ListItem>
              <asp:ListItem>PEDAGOG</asp:ListItem>
              <asp:ListItem>STUDENT</asp:ListItem>
        </asp:DropDownList>
        </div>
        </div>
        <div class="form-group">
        <div class="col-md-offset-2 col-md-4">
        <asp:Button ID="btn" class="btn btn-primary" Style="background: #ec1919;border: 1px solid #ec1919;margin-top: 15px;" runat="server"  Text="Vazhdo" OnClick="btn_Click"/>
        </div>
        </div>
    </div>
        <div id="pedag" runat="server" visible="false" >
            <h5 style="text-align:center;font-size:25px;">Plotësoni formën më poshtë për të përfunduar regjistrimin e pedagogut.</h5>
            <asp:ValidationSummary runat="server" CssClass="text-danger" />
            <div class="form-group">
        <div class="col-md-7">
            <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" CssClass="help-block" ControlToValidate="emp" Text="*" ErrorMessage="Plotësoni Emrin" ToolTip="Plotësoni Emrin" ForeColor="Red"></asp:RequiredFieldValidator>
            Emri<asp:TextBox ID="emp" class="form-control" runat="server"></asp:TextBox><br />
            </div>
        </div>
            <div class="form-group">
        <div class="col-md-7">
            <asp:RequiredFieldValidator ID="RequiredFieldValidator5" runat="server" CssClass="help-block" ControlToValidate="mbp" Text="*" ErrorMessage="Plotësoni Mbiemrin" ToolTip="Plotësoni Mbiemrin" ForeColor="Red"></asp:RequiredFieldValidator>
            Mbiemri<asp:TextBox ID="mbp" class="form-control" runat="server"></asp:TextBox><br />
            </div>
        </div>
            <div class="form-group">
        <div class="col-md-7">
            <asp:RequiredFieldValidator ID="RequiredFieldValidator6" runat="server" CssClass="help-block" ControlToValidate="atp" Text="*" ErrorMessage="Plotësoni Atesinë" ToolTip="Plotesoni Atesinë" ForeColor="Red"></asp:RequiredFieldValidator>
            Atësia<asp:TextBox ID="atp" class="form-control" runat="server"></asp:TextBox><br />
           </div>
        </div>
             <div class="form-group">
        <div class="col-md-7">
            <asp:RequiredFieldValidator ID="RequiredFieldValidator7" runat="server" CssClass="help-block" ControlToValidate="dtp" Text="*" ErrorMessage="Plotësoni Ditëlindjen" ToolTip="Plotësoni Ditëlindjen" ForeColor="Red"></asp:RequiredFieldValidator>
            Ditëlindja<asp:TextBox ID="dtp" class="form-control" runat="server" TextMode="Date" /><br />
            </div>
        </div>
            <div class="form-group">
        <div class="col-md-7">
            Gjinia
            <div class="radio-inline">
            <asp:RadioButton ID="F" runat="server"  GroupName="Gender" Text="Femër" />
                  </div>
            <div class="radio-inline">
            <asp:RadioButton ID="M" runat="server" GroupName="Gender" Text="Mashkull" Checked="true" />
            </div>
        </div>
            </div>
            <div class="form-group">
        <div class="col-md-7">
            <asp:RequiredFieldValidator ID="RequiredFieldValidator8" runat="server" CssClass="help-block" ControlToValidate="emailp" Text="*" ErrorMessage="Plotësoni Email-in" ToolTip="Plotësoni Email-in" ForeColor="Red"></asp:RequiredFieldValidator>
            Email<asp:TextBox ID="emailp" class="form-control" runat="server" TextMode="Email" /><br />
            <asp:RegularExpressionValidator ID="RegularExpressionValidator2" CssClass="help-block" runat="server" ControlToValidate="emailp" ErrorMessage="Format i gabuar i Email-it" ForeColor="Red" ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*">Email gabim</asp:RegularExpressionValidator>            
        </div>
        </div>
            <div class="form-group">
        <div class="col-md-7">
            <asp:RequiredFieldValidator ID="RequiredFieldValidator9" runat="server" CssClass="help-block" ControlToValidate="nrp" Text="*" ErrorMessage="Plotësoni Nr. e Telefonit" ToolTip="Plotësoni Nr. e Telefonit" ForeColor="Red"></asp:RequiredFieldValidator>
            Nr. Kontakti<asp:TextBox ID="nrp" class="form-control" runat="server" /><br />
            </div>
        </div>
            <div class="form-group">
        <div class="col-md-7">
            <asp:RequiredFieldValidator ID="RequiredFieldValidator10" runat="server" CssClass="help-block" ControlToValidate="titullp" Text="*" ErrorMessage="Plotësoni Titullin" ToolTip="Plotësoni Titullin" ForeColor="Red"></asp:RequiredFieldValidator>
            Titulli<asp:TextBox ID="titullp" class="form-control" runat="server" /><br />
            </div>
        </div>
            <div class="form-group">
        <div class="col-md-7">
            Departamenti<asp:DropDownList ID="dep" class="form-control btn btn-default" runat="server">
                          <asp:ListItem>DEPARTAMENTI I BIOLOGJISË</asp:ListItem>
                          <asp:ListItem>DEPARTAMENTI I INFORMATIKËS</asp:ListItem>
                          <asp:ListItem>DEPARTAMENTI I KIMISË INDUSTRIALE</asp:ListItem>
                          <asp:ListItem>DEPARTAMENTI I MATEMATIKËS</asp:ListItem>
                        </asp:DropDownList>
            </div>
        </div>
            <div class="form-group">
        <div class="col-md-offset-2 col-md-4">
        <asp:Button ID="Button1" runat="server" class="btn btn-success" Style="margin-top: 15px;background: #ec1919;border: 1px solid #ec1919;" Text="Shto Pedagog" OnClick="Button1_Click" />
        </div>
        </div>
        </div>
        <div id="student" runat="server" visible="false"> 
            <h5 style="text-align:center;font-size:25px;" >Plotësoni formën më poshtë për të përfunduar regjistrimin e studentit.</h5>
            <asp:ValidationSummary runat="server" CssClass="text-danger" />
            <div class="form-group">
             <div class="col-md-7">
              <asp:RequiredFieldValidator ID="RequiredFieldValidator11" runat="server" CssClass="help-block" ControlToValidate="emers" Text="*" ErrorMessage="Plotësoni Emrin" ToolTip="Plotësoni Emrin" ForeColor="Red"></asp:RequiredFieldValidator>
            Emri<asp:TextBox ID="emers" class="form-control" runat="server" /><br />
            </div>
        </div>
            <div class="form-group">
        <div class="col-md-7">
            <asp:RequiredFieldValidator ID="RequiredFieldValidator12" runat="server" CssClass="help-block" ControlToValidate="mbs" Text="*" ErrorMessage="Plotësoni Mbiemrin" ToolTip="Plotësoni Mbiemrin" ForeColor="Red"></asp:RequiredFieldValidator>
            Mbiemri<asp:TextBox ID="mbs" class="form-control" runat="server" /><br />
            </div>
        </div>
            <div class="form-group">
        <div class="col-md-7">
            <asp:RequiredFieldValidator ID="RequiredFieldValidator13" runat="server" CssClass="help-block" ControlToValidate="ats" Text="*" ErrorMessage="Plotësoni Atesinë" ToolTip="Plotesoni Atesinë" ForeColor="Red"></asp:RequiredFieldValidator>
            Atësia<asp:TextBox ID="ats" class="form-control" runat="server" /><br />
            </div>
        </div>
            <div class="form-group">
        <div class="col-md-7">
            <asp:RequiredFieldValidator ID="RequiredFieldValidator14" runat="server" CssClass="help-block" ControlToValidate="dts" Text="*" ErrorMessage="Plotësoni Ditëlindjen" ToolTip="Plotësoni Ditëlindjen" ForeColor="Red"></asp:RequiredFieldValidator>
            Ditëlindja<asp:TextBox ID="dts" class="form-control" runat="server" TextMode="Date" /><br />
            </div>
        </div>
            <div class="form-group">
        <div class="col-md-7">
            Gjinia
            <div class="radio-inline">
                <asp:RadioButton ID="Fe" runat="server" GroupName="Gjinia" Text="Femër" />
                </div>
            <div class="radio-inline">
            <asp:RadioButton ID="Ma" runat="server" GroupName="Gjinia" Text="Mashkull" Checked="true"/><br />
            </div>
            </div>
        </div>
            <div class="form-group">
        <div class="col-md-7">
            <asp:RequiredFieldValidator ID="RequiredFieldValidator15" runat="server" CssClass="help-block" ControlToValidate="drs" Text="*" ErrorMessage="Plotësoni Datën e Regjistrimit" ToolTip="Plotësoni Datën e Regjistrimit" ForeColor="Red"></asp:RequiredFieldValidator>
            Data e Regjistrimit<asp:TextBox ID="drs" class="form-control" runat="server" TextMode="Date" /><br />
            </div>
        </div>
            <div class="form-group">
        <div class="col-md-7">
            <asp:RequiredFieldValidator ID="RequiredFieldValidator16" runat="server" CssClass="help-block" ControlToValidate="vds" Text="*" ErrorMessage="Plotësoni Vendlindjen" ToolTip="Plotësoni Vendlindjen" ForeColor="Red"></asp:RequiredFieldValidator>
            Vendlindja<asp:TextBox ID="vds" class="form-control" runat="server" /><br />
            </div>
        </div>
            <div class="form-group">
        <div class="col-md-7">
            <asp:RequiredFieldValidator ID="RequiredFieldValidator17" runat="server" CssClass="help-block" ControlToValidate="vbs" Text="*" ErrorMessage="Plotësoni Vendbanimin" ToolTip="Plotësoni Vendbanimin" ForeColor="Red"></asp:RequiredFieldValidator>
            Vendbanimi<asp:TextBox ID="vbs" class="form-control" runat="server" /><br />
           </div>
        </div>
            <div class="form-group">
        <div class="col-md-7">
             <asp:RequiredFieldValidator ID="RequiredFieldValidator18" runat="server" CssClass="help-block" ControlToValidate="ems" Text="*" ErrorMessage="Plotësoni Email-in" ToolTip="Plotësoni Email-in" ForeColor="Red"></asp:RequiredFieldValidator>
            Email<asp:TextBox ID="ems" runat="server" class="form-control" TextMode="Email" /><br />
            <asp:RegularExpressionValidator ID="RegularExpressionValidator1" CssClass="help-block" runat="server" ControlToValidate="ems" ErrorMessage="Format i gabuar i Email-it" ForeColor="Red" ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*">Email gabim</asp:RegularExpressionValidator>            
        </div>
        </div>
            <div class="form-group">
        <div class="col-md-7">
            <asp:RequiredFieldValidator ID="RequiredFieldValidator19" runat="server" CssClass="help-block" ControlToValidate="nrs" Text="*" ErrorMessage="Plotësoni Nr. e Telefonit" ToolTip="Plotësoni Nr. e Telefonit" ForeColor="Red"></asp:RequiredFieldValidator>
            Nr. Kontakti<asp:TextBox ID="nrs" class="form-control" runat="server" /><br />
            </div>
        </div>
            <div class="form-group">
        <div class="col-md-7">
            <asp:RequiredFieldValidator ID="RequiredFieldValidator20" runat="server" CssClass="help-block" ControlToValidate="vit" Text="*" ErrorMessage="Plotësoni Vitin" ToolTip="Plotësoni Vitin" ForeColor="Red"></asp:RequiredFieldValidator>
            Viti<asp:TextBox ID="vit" runat="server" class="form-control" TextMode="Number" /><br />
            </div>
        </div>
            <div class="form-group">
        <div class="col-md-7">
            <asp:RequiredFieldValidator ID="RequiredFieldValidator21" runat="server" CssClass="help-block" ControlToValidate="gr" Text="*" ErrorMessage="Plotësoni Grupin" ToolTip="Plotësoni Grupin" ForeColor="Red"></asp:RequiredFieldValidator>
            Grupi<asp:TextBox ID="gr" class="form-control" runat="server" /><br />
            </div>
        </div>
            <div class="form-group">
        <div class="col-md-7">
            Departamenti<asp:DropDownList ID="deps" class="form-control btn btn-default" runat="server">
                          <asp:ListItem>DEPARTAMENTI I BIOLOGJISË</asp:ListItem>
                          <asp:ListItem>DEPARTAMENTI I INFORMATIKËS</asp:ListItem>
                          <asp:ListItem>DEPARTAMENTI I KIMISË INDUSTRIALE</asp:ListItem>
                          <asp:ListItem>DEPARTAMENTI I MATEMATIKËS</asp:ListItem>
                       </asp:DropDownList><br />
           </div>
        </div>
            <div class="form-group">
        <div class="col-md-7">
             Dega<asp:DropDownList ID="dega" class="form-control btn btn-default" runat="server">
                  <asp:ListItem>BACHELOR NË BIOLOGJI</asp:ListItem>
                  <asp:ListItem>BACHELOR NË INFORMATIKË</asp:ListItem>
                  <asp:ListItem>BACHELOR NË TEKNOLOGJI INFORMACIONI DHE KOMUNIKIMI</asp:ListItem>
                  <asp:ListItem>BACHELOR NË KIMI DHE TEKNOLOGJI USHQIMORE</asp:ListItem>
                  <asp:ListItem>MASTER I SHKENCAVE NË KIMI INDUSTRIALE</asp:ListItem>
                  <asp:ListItem>MASTER PROFESIONAL NË MATEMATIKË TË APLIKUAR</asp:ListItem>
                </asp:DropDownList>
            </div>
        </div>
            <div class="form-group">
        <div class="col-md-offset-2 col-md-4">
                <asp:Button ID="Button2" runat="server" class="btn btn-success" Style="margin-top: 15px;background: #ec1919;border: 1px solid #ec1919;" Text="Shto Student" OnClick="Button2_Click" />
        </div>
        </div>    
        </div>
        
         </div> 
      </div>
    </form>
                 </div>
              </div>      
            </div>
            <footer class="footer text-center"> 2018 &copy; Fakulteti i Shkencave Të Natyrës | Universiteti i Tiranës </footer>
<script src="../Assets/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js"></script>
    <script src="../Assets/js/jquery.slimscroll.js"></script>
    <script src="../Assets/js/custom.min.js"></script>
</body>
</html>
